name: Push_Run
on: push

jobs:
  Google_API:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Step 1 - Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Step 2 - Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Step 3 - Install virtualenv
        run: |
          python -m pip install virtualenv
          virtualenv -p python3.8 .env
          source .env/bin/activate

      - name: Step 4 - Install dependencies
        run: |
          pip install -r requirements.txt


      - name: Step 5 - Run test suite
        run: |
          pytest -s -v --junit-xml=funnelbeam_report.xml
